# Generated by Django 4.2.3 on 2023-08-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_avatar_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
