# Generated by Django 4.2.3 on 2023-08-07 13:41

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_avatar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, editable=False, max_length=72)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('story', models.TextField()),
                ('photo', models.ImageField(upload_to='images/photo')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, editable=False, max_length=72)),
                ('title', models.CharField(max_length=30)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='images/projects')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('lvl', models.IntegerField(validators=[app.models.valifator_month])),
            ],
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/galery')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.about')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=30)),
                ('type_of_education', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('how_many_month', models.IntegerField(validators=[app.models.valifator_month])),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.about')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='app.skill'),
        ),
    ]
