# Generated by Django 4.2.3 on 2023-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_about_projects_skill_galery_education_about_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
