# Generated by Django 4.2.3 on 2023-08-08 22:54

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_projects_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='lvl',
            field=models.IntegerField(validators=[app.models.valifator_lvl]),
        ),
    ]
