# Generated by Django 4.2.3 on 2023-08-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_skill_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='lvl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
