# Generated by Django 4.2.3 on 2023-08-08 23:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_skill_lvl_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='lvl',
            field=models.IntegerField(validators=[app.models.valifator_month]),
        ),
    ]
